# Generated by Django 4.1.1 on 2022-10-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_friend_profile_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="friends",
        ),
    ]
