# Generated by Django 4.1.1 on 2022-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_profile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(related_name="my_friends", to="chat.friend"),
        ),
    ]
