# Generated by Django 4.1.1 on 2022-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_datecompleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
